# Generated by Django 5.2.3 on 2025-06-29 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 1, 1, 51, 754248, tzinfo=datetime.timezone.utc)),
        ),
    ]
