# Generated by Django 5.2.3 on 2025-06-26 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_conversation_emailverification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 1, 59, 8, 627532, tzinfo=datetime.timezone.utc)),
        ),
    ]
