# Generated by Django 5.2.3 on 2025-06-26 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 2, 9, 10, 322866, tzinfo=datetime.timezone.utc)),
        ),
    ]
