# Generated by Django 5.2.3 on 2025-06-29 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 1, 3, 54, 169256, tzinfo=datetime.timezone.utc)),
        ),
    ]
