# Generated by Django 5.2.3 on 2025-06-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 19, 46, 16, 526832, tzinfo=datetime.timezone.utc)),
        ),
    ]
