# Generated by Django 5.2.3 on 2025-06-27 07:40

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='campuses'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 7, 40, 18, 370377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery/images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='gallery/videos'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='news'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='staff'),
        ),
    ]
