# Generated by Django 5.2.3 on 2025-06-27 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_campus_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 13, 34, 42, 592789, tzinfo=datetime.timezone.utc)),
        ),
    ]
