# Generated by Django 5.2.3 on 2025-06-29 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 0, 17, 10, 485159, tzinfo=datetime.timezone.utc)),
        ),
    ]
