# Generated by Django 5.2.3 on 2025-06-29 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 3, 25, 10, 664069, tzinfo=datetime.timezone.utc)),
        ),
    ]
