# Generated by Django 5.2.3 on 2025-07-23 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_youtubevideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='qualification',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='office_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='office_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 18, 26, 8, 232998, tzinfo=datetime.timezone.utc)),
        ),
    ]
