# Generated by Django 5.2.3 on 2025-07-24 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_academicannouncement_academiccalendar_coursecatalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 5, 45, 42, 142910, tzinfo=datetime.timezone.utc)),
        ),
    ]
