# Generated by Django 5.2.3 on 2025-07-24 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='SchoolClass',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 7, 37, 53, 223551, tzinfo=datetime.timezone.utc)),
        ),
    ]
