# Generated by Django 5.2.3 on 2025-07-28 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_emailverification_activation_code_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 9, 11, 2, 610918, tzinfo=datetime.timezone.utc)),
        ),
    ]
