# Generated by Django 5.2.3 on 2025-07-28 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 9, 30, 32, 997296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='result',
            name='term',
            field=models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term')], max_length=1),
        ),
    ]
