# Generated by Django 5.2.3 on 2025-07-29 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_student_address_remove_student_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 11, 28, 54, 484537, tzinfo=datetime.timezone.utc)),
        ),
    ]
