# Generated by Django 5.2.3 on 2025-08-03 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 14, 49, 50, 876582, tzinfo=datetime.timezone.utc)),
        ),
    ]
