# Generated by Django 5.2.3 on 2025-08-04 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_result_unique_together_result_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 6, 24, 35, 29298, tzinfo=datetime.timezone.utc)),
        ),
    ]
