# Generated by Django 5.2.3 on 2025-08-04 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 6, 25, 36, 280880, tzinfo=datetime.timezone.utc)),
        ),
    ]
