# Generated by Django 5.2.3 on 2025-08-04 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='classes_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='main.schoolclass'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 7, 19, 19, 715673, tzinfo=datetime.timezone.utc)),
        ),
    ]
