# Generated by Django 5.2.3 on 2025-08-04 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_staffmember_classes_taught_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='classes_taught',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='subjects_taught',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 8, 23, 0, 628903, tzinfo=datetime.timezone.utc)),
        ),
    ]
