# Generated by Django 5.2.3 on 2025-08-04 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_staffmember_classes_taught_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 8, 25, 41, 92161, tzinfo=datetime.timezone.utc)),
        ),
    ]
