# Generated by Django 5.2.3 on 2025-08-07 07:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_emailverification_activation_code_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 7, 24, 18, 37663, tzinfo=datetime.timezone.utc)),
        ),
    ]
