# Generated by Django 5.2.3 on 2025-08-08 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_youtubevideo_approved_at_youtubevideo_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 9, 7, 28, 19, 850645, tzinfo=datetime.timezone.utc)),
        ),
    ]
