# Generated by Django 5.2.3 on 2025-08-11 09:37

import cloudinary.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='academic_calendars'),
        ),
        migrations.AlterField(
            model_name='coursecatalog',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='course_catalogs'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 9, 37, 46, 374081, tzinfo=datetime.timezone.utc)),
        ),
    ]
