# Generated by Django 5.2.3 on 2025-08-11 09:40

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_academiccalendar_file_alter_coursecatalog_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='academic_calendars'),
        ),
        migrations.AlterField(
            model_name='coursecatalog',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='course_catalogs'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 9, 40, 16, 537909, tzinfo=datetime.timezone.utc)),
        ),
    ]
