# Generated by Django 5.2.3 on 2025-09-10 06:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_activitylog_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 11, 6, 54, 56, 814450, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ParentOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parent')),
            ],
        ),
    ]
