# Generated by Django 5.2.3 on 2025-09-11 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_emailverification_activation_code_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentotp',
            name='sent_to_email',
            field=models.EmailField(default=200000, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 6, 43, 6, 36066, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
