# Generated by Django 5.2.3 on 2025-09-16 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_inventorycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 17, 8, 43, 21, 967729, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
