# Generated by Django 5.2.3 on 2025-09-16 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 17, 8, 52, 36, 472847, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='total_value',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=14),
        ),
    ]
