# Generated by Django 5.2.3 on 2025-09-17 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_emailverification_activation_code_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 8, 54, 3, 392017, tzinfo=datetime.timezone.utc)),
        ),
    ]
