# Generated by Django 5.2.3 on 2025-09-17 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_emailverification_activation_code_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 9, 45, 11, 541364, tzinfo=datetime.timezone.utc)),
        ),
    ]
