# Generated by Django 5.2.3 on 2025-09-19 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_result_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 5, 37, 43, 221075, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'term', 'academic_year', 'week_number')},
        ),
    ]
