# Generated by Django 5.2.3 on 2025-09-19 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_emailverification_activation_code_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='activation_code_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 7, 27, 51, 216674, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='result',
            name='academic_year',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
